image:
  name: gitpod/workspace-full:latest

tasks:
  - name: Setup Environment
    init: |
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt

ports:
  - port: 8080
    onOpen: open-preview