image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    init: |
      pip install -r requirements.txt

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python